version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "aledger.controllers.http:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - PYTHONUNBUFFERED=1
